### ISSUE TITLE
heatmap displays circles at wrong location

### ISSUE THREAD

**Issue by kolesar-andras** [Telenav/improve-osm-plugin#11]
Some heat circles are displayed far away from their real location.

Example:
http://improve-osm.org/#47.4903259,19.0486622,14/OPEN/true,1-1-1/true,1-0-0/true,1-1

Circle is located at Szarvas tér while possibly oneway street Mihály utca is on Gellérthegy, distance is 600 meters.

**Comment by beataj-telenav** [comment]
This is a known issue, currently we are working on a better clustering solution.
