### ISSUE TITLE
improve-osm.org: login discards current position/zoom

### ISSUE THREAD

**Issue by kerosin** [Telenav/improve-osm-plugin#12]
cause there is no improve-osm.org repo, I will report here:

I usually sight a region by sliding and zooming and then want to edit this issues (usually forgot to login before).

After login current lat/lon and zoom is discarded and I have to find that region again. That is just a minor improvement, but super annoying for users :grinning:

**Comment by beataj-telenav** [comment]
Closing since we have removed the web application.
