### ISSUE TITLE
source tag on ways with improve_osm_tn value

### ISSUE THREAD

**Issue by pierzen** [Telenav/improve-osm-plugin#13]
I see that there were 9734 ways added to OSM with  the tag source=improve_osm_tn added to the way to report usage of the ImproveOsm.

The appropriate source code refering to imagery is added on the changeset. But the usage of  source tag on the way adds confusion and is to my point of view inappropriate since the source tag is used to report imagery. 

An other tag should be used and could be simply added on the changeset.

**Comment by beataj-telenav** [comment]
The plugin doesn't add automatically any source tag. It is up to the user to add a source tag corresponding to the edit.
