### ISSUE TITLE
No map issues identified in Ireland

### ISSUE THREAD

**Issue by mackerski** [Telenav/improve-osm-plugin#15]
Using the plugin in JOSM, I can see issue circles in various colours covering much of Europe and into north Africa. None are visible in Ireland. Maybe we just have a very successful community fixing issues the moment they arise, but is it possible that no analysis is taking place?

**Comment by beataj-telenav** [comment]
The ImproveOSM issues are identified in areas where we have navigation data. In Ireland, we have almost no data, so this is why we don't have any ImproveOSM issue.
