### ISSUE TITLE
Oneway issues don't show up when zooming in

### ISSUE THREAD

**Issue by mvexel** [Telenav/improve-osm-plugin#17]
The clusters do show up but not the individual issues when I zoom in:

![nooneway](https://user-images.githubusercontent.com/120452/32956260-88ae968a-cb75-11e7-9e33-a1dc2d9f12b1.gif)

**Comment by jBeata** [comment]
Did you set any filters for the One-way layer? If yes try clearing the filters.

**Comment by mvexel** [comment]
Makes no difference. I clicked 'reset' on the filter settings, and it looks like this: 

<img width="662" alt="screenshot 2017-11-17 10 44 07" src="https://user-images.githubusercontent.com/120452/32961062-592c31ec-cb84-11e7-87fb-299981431545.png">

Same result.

**Comment by jBeata** [comment]
I will check the issue on Monday. Thanks for reporting.

**Comment by beataj-telenav** [comment]
The issue was fixed.
