### ISSUE TITLE
web map shows at most 2 as number of clustered items

### ISSUE THREAD

**Issue by kolesar-andras** [Telenav/improve-osm-plugin#7]
My very first place at improve-osm.org was a road crossing with turn restriction confidences. Map displayed two issues. I have invalidated one of them, then map still displayed 2. This was confusing. I did not know whether this website does not hide items immediately or did not save my feedback. Then I have clicked the circle displaying 2 again. One of the issues have changed, another issue was displayed instead of my first invalidated issue.

Map should display the real number of items for correct feedback.

**Comment by beataj-telenav** [comment]
Thanks for the report. We are working on fixing this issue.
