### ISSUE TITLE
 plugin does not send reports when another layer is active

### ISSUE THREAD

**Issue by kolesar-andras** [Telenav/improve-osm-plugin#8]
Steps to reproduce: navigate to a place where a MissingRoad tile is shown. Select rectangle, opacity increases, details appear in MissingRoads panel, green lock and red exclamation mark buttons get enabled. Load OSM data to a data layer. Activate OSM data layer with green checkmark in layer list. Press green lock button (mark selected items as solved). Enter text, press OK. Dialog hides, tile remains there. Does not get marked as solved.

Workaround: activate MissingRoads layer and repeat mark as solved action. When MissingRoads layer is active, reports are sent to the server, tiles disappear.

The same issue affects all three tools: MissingRoads, Traffic Flow Direction, Turn Restriction.

**Comment by beataj-telenav** [comment]
This is an intended behaviour. You can send reports only if one of the ImproveOsm layers is active.

**Comment by kolesar-andras** [comment]
> You can send reports only if one of the ImproveOsm layers is active.

You can compose a report any time, I mean even if no Improve OSM layer is active. The *huge* problem is that report is not sent, no error message comes. It is frustrating.
